matrix:
 include:
 - language: node_js # Your language e.g. node_js, python
   node_js:
   - '10' # node_js version
   dist: trusty
   addons:
    sonarcloud:
      organization: swsnu
      token:
        secure: 2e079b3cf2fb83ff3276254523e3fd7444229042 
   install: # Script to install required packages
   - yarn install
   script: # Script to test your build
   - ./node_modules/.bin/eslint src
   - yarn test --coverage --watchAll=false
   - sonar-scanner