matrix:
 include:
 - language: node_js # Your language e.g. node_js, python
   node_js:
   - '10' # node_js version
   before_install:
   - cd frontend
   install: # Script to install required packages
   - yarn install
   script: # Script to test your build
   - ./node_modules/.bin/eslint src
   - yarn test --coverage --watchAll=false

notifications:
  slack: swpp-team8:NPIs4kBcXYNcBwa9Z5TIrkk0