# Generated by Django 2.2.5 on 2019-11-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellme', '0002_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
