# Generated by Django 2.2.6 on 2019-12-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellme', '0002_auto_20191122_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='debatecomment',
            name='date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
