# Generated by Django 2.2.6 on 2019-12-03 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tellme', '0003_auto_20191202_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='edit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
