export const POST_SIGN_UP = 'POST_SIGN_UP';
export const POST_SIGN_IN = 'POST_SIGN_IN';
export const GET_SIGN_OUT = 'GET_SIGN_OUT';
export const GET_USER = 'GET_USER';
export const POST_DOCUMENT = 'POST_DOCUMENT';
export const GET_DOCUMENT = 'GET_DOCUMENT';
export const PUT_DOCUMENT = 'PUT_DOCUMENT';
export const POST_PHOTO = 'POST_PHOTO';
export const GET_PHOTO = 'GET_PHOTO';
export const PUT_PHOTO = 'PUT_PHOTO';
export const GET_DEBATES = 'GET_DEBATES';
export const POST_DEBATE = 'POST_DEBATE';
export const GET_DEBATE = 'GET_DEBATE';
export const GET_DEBATE_COMMENTS = 'GET_DEBATE_COMMENTS';
export const POST_DEBATE_COMMENT = 'POST_DEBATE_COMMENT';
export const POST_PETITION = 'POST_PETITION';
export const GET_ALL_PETITIONS = 'GET_ALL_PETITIONS';
export const GET_PETITION = 'GET_PETITION';
export const GET_PETITION_BY_TITLE = 'GET_PETITION_BY_TITLE';
export const GET_MY_PETITIONS = 'GET_MY_PETITIONS';
export const GET_PETITION_COMMENTS = 'GET_PETITION_COMMENTS';
export const POST_PETITION_COMMENT = 'POST_PETITION_COMMENT';
export const PUT_PETITION_VOTE = 'PUT_PETITION_VOTE';   // Wiki에 추가 필요
// Statistic에 해당하는 것은 아직 안 만듦