# Generated by Django 2.2.6 on 2019-11-05 16:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('category', models.TextField()),
                ('link', models.TextField()),
                ('tag', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(default=datetime.datetime(2019, 12, 5, 16, 18, 50, 81462))),
                ('votes', models.IntegerField()),
                ('status', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PetitionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('petition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hearus.Petition')),
            ],
        ),
    ]
