# Generated by Django 2.2.5 on 2019-10-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='petition',
            name='link',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='tag',
        ),
        migrations.AddField(
            model_name='petition',
            name='link',
            field=models.ManyToManyField(to='hearus.Link'),
        ),
        migrations.AddField(
            model_name='petition',
            name='tag',
            field=models.ManyToManyField(to='hearus.Tag'),
        ),
    ]
