# Generated by Django 2.2.6 on 2019-11-05 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 5, 16, 19, 27, 656558)),
        ),
    ]
