# Generated by Django 2.2.5 on 2019-11-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
