# Generated by Django 2.2.5 on 2019-10-31 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearus', '0002_auto_20191030_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.URLField(),
        ),
    ]
