# Generated by Django 2.2.5 on 2019-11-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearus', '0003_auto_20191031_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='link',
        ),
        migrations.AddField(
            model_name='petition',
            name='link',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='petition',
            name='tag',
        ),
        migrations.AddField(
            model_name='petition',
            name='tag',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
