# Generated by Django 2.2.6 on 2019-11-07 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearus', '0005_auto_20191106_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 7, 7, 15, 24, 234208)),
        ),
    ]
