# Generated by Django 2.2.5 on 2019-11-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearus', '0006_auto_20191107_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
