# Generated by Django 2.2.5 on 2019-11-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearus', '0007_auto_20191107_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
