# Generated by Django 2.2.6 on 2019-11-22 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hearus', '0007_auto_20191107_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petitioncomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
